### ISSUE TITLE
Patch for DSM 6.2.3-25426

### ISSUE THREAD

**Issue by lalafa976** [Adam5Wu/DSMNetworkingMod#1]
Thanks for the great patch! Working on my 918+

Do you have any plans to release a new patch for version 6.2.3-25426?

William

**Comment by Adam5Wu** [comment]
Yeap. I just upgraded myself to the latest DSM. Will push a new version soon. :D

**Comment by Adam5Wu** [comment]
Done. Let me know if you have any issue!
