### ISSUE TITLE
VLAN assigned to interfaces not participating in bond

### ISSUE THREAD

**Issue by rdgerken** [Adam5Wu/DSMNetworkingMod#2]
Hi,

I was hoping you could help me out.  I was trying to roll out your solution here, but I'm only using eth0 and eth1 in a bond, whereas eth2 and eth3 are independent.  What's happening is the VLAN tag assigned to ovs_bond0 is getting assigned to eth2 and eth3, even though I have removed them from the slave list in the ifcfg files.  Do you know why this is happening?  I think it must be something in the script that is assigning them to the VLAN, but I can't rule out a configuration file issue either.

I have followed your example configuration, but have removed eth2 and eth3 from the slave_list.

Thanks for sharing this project.

TIA!

Here are my config files:

DEVICE=ovs_bond0
BOOTPROTO=dhcp
ONBOOT=yes
IPV6INIT=off
TYPE=OVS
BOND_MODE=balance-tcp
BONDING_OPTS="bond_mode=balance-tcp lacp=active"
PRIMARY=eth0
SLAVE_LIST="eth0 eth1 "
OVS_VLAN_ID=6
OVS_PATCH="patch0a:patch0b "

DEVICE=ovs_bond1
ONBOOT=yes
BOOTPROTO=dhcp
IPV6INIT=off
TYPE=OVS
OVS_VLAN_ID=15
OVS_PARENT=ovs_bond0
OVS_MACADDR=00:11:32:X
SLAVE_LIST="eth0 eth1 "

DEVICE=ovs_bond2
ONBOOT=yes
BOOTPROTO=dhcp
IPV6INIT=off
TYPE=OVS
OVS_VLAN_ID=10
OVS_PARENT=ovs_bond0
OVS_MACADDR=00:11:32:X
SLAVE_LIST="eth0 eth1 "

DEVICE=ovs_bond99
BOOTPROTO=none
ONBOOT=yes
TYPE=OVS
IPV6INIT=off
OVS_VIRTUAL=yes
OVS_PATCH="patch0b:patch0a "
SLAVE_LIST="eth0 eth1 "

DEVICE=ovs_eth0
ONBOOT=yes
BOOTPROTO=dhcp
PRIMARY=eth0
TYPE=OVS
SLAVE=yes

DEVICE=ovs_eth1
ONBOOT=yes
BOOTPROTO=dhcp
PRIMARY=eth1
TYPE=OVS
SLAVE=yes

#Don't want as part of the bond or VLAN 6, but comes up as VLAN6
DEVICE=ovs_eth2
BOOTPROTO=static
ONBOOT=yes
PRIMARY=eth2
TYPE=OVS
IPADDR=X.X.X.X
NETMASK=255.255.255.0
IPV6INIT=off
SLAVE=no

#Don't want as part of the bond or VLAN 6, but comes up as VLAN6
DEVICE=ovs_eth3
BOOTPROTO=dhcp
ONBOOT=yes
PRIMARY=eth3
TYPE=OVS
IPV6INIT=off
SLAVE=no

**Comment by Adam5Wu** [comment]
Sorry for the late reply, haven't got much time to check my projects here. :P

I don't think the extra VLAN is due to any of the logic in this patch.

However, in the official script, there is the `do_start_vlan_interface()`, which pulls some vlan configurations from `/etc/sysconfig/network-scripts/ifcfg-*` and perform some setup. Could you check whether you have any residual settings in the `ifcfg-*` files?
