### ISSUE TITLE
Patch: command not found

### ISSUE THREAD

**Issue by mkrasselt1** [Adam5Wu/DSMNetworkingMod#3]
Tried to apply this patch,
I am used to linux consoles but this synology thing dosnt seem to have some package manager to apply this patch, whats a suitable alternative?
Thought it might be a git command, no...

**Comment by Adam5Wu** [comment]
Interesting... I never realized that Synology stripped the `patch` command! That's sneaky...

I think you could scp to a standard Linux environment and apply patch there.

Alternatively, if you really want to do everything on that box, you could install docker and create a container with standard Linux environment, and move files via a shared folder... :P

**Comment by mkrasselt1** [comment]
What a great solution you gave :)
I did not think of this!
Thanks this solved it :)
