### ISSUE TITLE
will the patch work with DS920+?

### ISSUE THREAD

**Issue by doomsat** [Adam5Wu/DSMNetworkingMod#4]
Hello,

I have DS920+ witch comes with 2 Ethernet ports therefore I was wondering if your patch will work fine with it? when I was looking at the config files I noticed that eth3 is there although I don't know if this was meant to be virtual or physical.

I tried a lot of modifications but with no luck, like you stated in the readme, once Vswitch is active everything is destroyed, really appreciate the work you have done.

and are there any plans to mod for DSM 7?

Regards.

**Comment by Adam5Wu** [comment]
I think the mods are hardware agnostic, so they should work on your box -- as long as you use the right DSM version.

I haven't upgraded to DSM 7, for the fear I heard they've locked down the box and getting root access may be hard.
All of my boxes are currently for "critical production" uses and I have no spare hardware to experiment with... :P

**Comment by doomsat** [comment]
Hello,

Yes root access is still there, I even reverted back to DSM 6 and tried your patch, but in the end I just gave up and accepted that it is hard to run VMs on sinology as I need a lot more resources witch the synology cannot handle so I ended up with a VM Host xD.

the multiple VLAN trick still works though this is what I configured on DSM 7 now.
